name: Build binary

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build binary
        run:  cd ../../DynArray/ | make
      - name: Upload binary artifact
        uses: actions/upload-artifact@v2
        with:
            name: binary-artefact
            path: ../../DynArray/
   
